project:
  type: website

website:
  title: "dqc-workshop"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - tutorial.qmd

format:
  html:
    theme:
      light: [cosmo, qc-light-theme.scss]
      dark: [cosmo, qc-dark-theme.scss]
    css: styles.css
    toc: true



